### ISSUE TITLE
Binary XML file line #8: You must supply a layout_height attribute

### ISSUE THREAD

**Issue by echthard** [javiersantos/MaterialStyledDialogs#12]
`java.lang.RuntimeException: Binary XML file line #8: You must supply a layout_height attribute.
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5755)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:5890)
	at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1815)
	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1727)
	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.github.javiersantos.materialstyleddialogs.MaterialStyledDialog.initStyle(MaterialStyledDialog.java:324)
	at com.github.javiersantos.materialstyleddialogs.MaterialStyledDialog.build(MaterialStyledDialog.java:268)
	at com.github.javiersantos.materialstyleddialogs.MaterialStyledDialog.show(MaterialStyledDialog.java:307)
	at com.sjoprz.activity.Main$2.run(Main.java:197)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4947)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by javiersantos** [comment]
Could you check the latest library update? Thanks!
```gradle
dependencies {
	compile 'com.github.javiersantos:MaterialStyledDialogs:451e6411da'
}

**Comment by echthard** [comment]
I can't reproduce it, unfortunately. I see this error coming from a few of my app users. They all have Android API 16.

Can something be build in the library, or do I have to check it in my app and show a normal dialog for API 16?

**Comment by javiersantos** [comment]
I am almost sure that the latest change should fix the issue. It was an issue affecting to users with a small screen size (less than 470dp x 320dp). Normally, the users with Android 4.1 (API 16) use this screens size.

```Javascript
dependencies {
    compile 'com.github.javiersantos:MaterialStyledDialogs:1.2.2'
}
```

**Comment by echthard** [comment]
Ah ok, I will use the update and let you know if I still see the error. 
Thanks Javier!

**Comment by javiersantos** [comment]
Great! Thank you for letting me know.
